name: Trigger auto deployment for container-app-brzazxpms5m3u

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-brzazxpms5m3u-AutoDeployTrigger-2c64a621-c8ef-4cbd-9eed-24bf63f10cb8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPBRZAZXPMS5M3U_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPBRZAZXPMS5M3U_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPBRZAZXPMS5M3U_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPBRZAZXPMS5M3U_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPBRZAZXPMS5M3U_REGISTRY_PASSWORD }}
          containerAppName: container-app-brzazxpms5m3u
          resourceGroup: expresssampleb1a78b18
          imageToBuild: default/container-app-brzazxpms5m3u:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


